name: Code linting

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      # build check:

      - name: Run build
        run: ./gradlew build --stacktrace

      # diktat:

      - name: Run diktat
        run: ./gradlew diktatCheck

      - name: Archive diktat results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diktat-report
          path: build/reports/diktat.html

      # detekt:

      - name: Run detekt
        run: ./gradlew customDetekt --stacktrace

      - name: Archive detekt results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt.html
